### ISSUE TITLE
habari and PHP 7.2

### ISSUE THREAD

**Issue by kaslak** [habari/habari#655]
I get a white page switching to PHP 7.2 - any way to cure this?
And... is the project still active? ... somewhere, somehow, sometimes?

**Comment by dvector** [comment]
Please note this is just a hack to get my own sites back up and running. 
A few edits are required in the following files:

\system\index.php 
       Move session_start(); to line 15

\system\classes\curlrequestprocessor.php
       line 177 remove or comment out // $this->headers[ $pieces[0] ] = $pieces[1];
       line 183 remove or comment out // $this->headers[ $pieces[0] ] = $pieces[0];

\system\classes\session.php
      line 53 remove or comment out // session_set_cookie_params( null, $path, null, $secure );
      line 72  remove or comment out // call_user_func_array('session_set_save_handler', $handlers);

\system\classes\update.php
       line 13 the http or https url 'https://beacon.habariproject.org/' appears no longer to be maintained

If a theme uses count( $posts ) PHP 7 will throw an ERROR posts not countable.

**Comment by kaslak** [comment]
Thanks, mate, will check that... Cheers

**Comment by kaslak** [comment]
What Version do you use - 
my index.php doesn't have session_start();
there's Session::init();

**Comment by kaslak** [comment]
NOPE, didn't work for me - white page still.

I run habari 0.92 // and checked with PHP 7.2

**Comment by dvector** [comment]
I'm using version 0.9.2 and PHP 7.2.9

Oops sorry, add session_start() at line 15 and keep Session::init() where it is.

Just had another look and I also changed:
\system\classes\theme.php public function act_display() 
At line 244 or thereabouts replace: if ( $posts !== false && count( $posts ) > 0 ) 
  with  if ( $posts !== false && $posts instanceof POST)

If above doesn't work you'll need to enable the display of php errors or look in the server log to narrow down any other unhandled exceptions.

**Comment by dvector** [comment]
Here's a copy of my working habari system

Updated: [habari_system_php72.zip](https://github.com/habari/habari/files/3133181/habari_system_php72.zip)

**Comment by kaslak** [comment]
Thanks!

I tried your /system/  - dropping this error

Fatal error: Uncaught Error: Class 'debug' not found in .../system/classes/error2.php:79 Stack trace: #0 [internal function]: Error2::exception_handler(Object(Error)) #1 {main} thrown in .../system/classes/error2.php on line 79

Error: Uncaught Error: Class 'debug' not found in .../system/classes/error2.php:79
Stack trace:
#0 [internal function]: Error2::exception_handler(Object(Error))
#1 {main}
  thrown in .../system/classes/error2.php line 79

BTW interesting error2.php

Mine, which is the standard /system/ on this gives me:

Deprecated: Function create_function() is deprecated in .../system/classes/habarilocale.php on line 261

Deprecated: Function create_function() is deprecated in .../system/classes/habarilocale.php on line 261

Warning: session_start(): Failed to read session data: user (path: .../.tmp) in .../system/classes/session.php on line 78

Fatal error: Uncaught Error: Call to undefined method Error::raise() in .../system/classes/habarilocale.php:148 Stack trace: #0 .../system/classes/habarilocale.php(79): HabariLocale::load_file('simpleblock', '/...') #1 .../system/classes/pluggable.php(91): HabariLocale::load_pluggable_domain('simpleblock', '/...') #2 .../user/plugins/simple-block_0.9-1.0/simpleblock.plugin.php(14): Pluggable->load_text_domain('simpleblock') #3 .../system/classes/plugins.php(98): SimpleBlock->action_init() #4 .../system/index.php(175): Plugins::act('init') #5 .../index.php(21): require('/...') #6 {main} thrown in .../system/classes/habarilocale.php on line 148

Too much for me ;)

**Comment by dvector** [comment]
I've reworked using a clean Habari 0.9.2 [habari_system_php72.zip](https://github.com/habari/habari/files/3133189/habari_system_php72.zip)

Working at https://33v.co.uk/dev/habari/ 

The re-named file error2.php and its class name because in php 7.2 'Error' is a reserved class name. The other errors and fixes are in issues.txt in the zip. There's a number of create_function() that need alternatives but they don't appear to get called in a simple install.

Habari Version: 0.9.2
Active Theme: Wazi
Plugins: None
PHP Version 7.2
Database sqlite

It needs proper developers to fix and keep the project alive

**Comment by kaslak** [comment]
Thanks again. I gave up. Scripting my own - not as sophisticated as habari, by far not... But for a simple daily use. The project is dead, I think.

**Comment by chrisjdavis** [comment]
It’s as dead as we want it to be. I still use and work with Habari everyday. I build stuff on it, as well as use it for my various sites. I would love to put some time into it soon, and probably will, for my own edification.

**Comment by miklb** [comment]
🤔

**Comment by illyaking** [comment]
:/
Yeah... I would as well. Its a shame really because I really like it.
